### ISSUE TITLE
Gstreamer Issue

### ISSUE THREAD

**Issue by cdaher78** [BreeeZe/rpos#129]
I've built from source using gst-build (branch 1.18.0) and this is the error I'm getting:

```rtspServer: 
** (python:1127): WARNING **: 11:57:16.753: Failed to load shared library 'libgstrtspserver-1.0.so.0' referenced by the typelib: /usr/lib/arm-linux-gnueabihf/libgstrtspserver-1.0.so.0: undefined symbol: GST_CAT_DEFAULT

rtspServer: ./python/gst-rtsp-launch.py:60: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.server = GstRtspServer.RTSPServer()
Traceback (most recent call last):
  File "./python/gst-rtsp-launch.py", line 362, in <module>
    codec)
  File "./python/gst-rtsp-launch.py", line 60, in __init__
    self.server = GstRtspServer.RTSPServer()
TypeError: could not get a reference to type class

rtspServer exited with code: 1
```
 Anyone faced some similar issue? 

I don't know how to solve this.

**Comment by DoubleChuang** [comment]
https://github.com/BreeeZe/rpos#step-5c---option-3-using-gstreamer-rtsp-server

**Comment by cdaher78** [comment]
I started from the beginning with a fresh Buster image and followed step by step. It worked!

Thanks @DoubleChuang
